### ISSUE TITLE
Are there any way to disable displaying bars?

### ISSUE THREAD

**Issue by miratcan** [Rockhopper-Technologies/enlighten#11]
I have written some doctests in my script. But when running doctests I don't want to display bars. Are there any method to hide them? Or some kind of manage to do that?

**Comment by avylove** [comment]
Both [enlighten.Manager()](https://python-enlighten.readthedocs.io/en/stable/api.html#enlighten.Manager) and [enlighten.Counter()](https://python-enlighten.readthedocs.io/en/stable/api.html#enlighten.Counter) have an `enabled` parameter and instance value which can be used to enable or disable the output.

There's an [example](https://python-enlighten.readthedocs.io/en/stable/patterns.html#enable-disable) in the docs of reading from a config object, but you can also do one of the following:

    # Enable for all counters spawned from manager
    enlighten.get_manager(enabled=False)

    # Disable for only select counters spawned from a manager
    manger =  enlighten.get_manager()
    manger.counter(total=100, enabled=False)

    # Disable for a singleton counter
    enlighten.Counter(total=100, enabled=False)

Or to change later:
   
    manger =  enlighten.get_manager()
    manager.enabled = False

    counter = manger.counter(total=100)
    counter.enabled = False

    enlighten.Counter(total=100)
    counter.enabled = False

**Comment by avylove** [comment]
Going to close this. Let me know if you run into any issues.
