### ISSUE TITLE
Sub-counters not available in counter_format

### ISSUE THREAD

**Issue by edmcman** [Rockhopper-Technologies/enlighten#12]
I would really like to display some other statistics/counters when in counter mode.  It seems like the only way to do this is using sub-counters, but if I try to access a sub-counter in a `counter_format`, I get an error such as:

```
KeyError: 'count_1'
```

**Comment by avylove** [comment]
I think it would help to see some of the code. Can you post what you're doing or some sample code that creates the condition?

**Comment by edmcman** [comment]
``` python
#!/usr/bin/python

import enlighten

# Setup progress bar
manager = enlighten.get_manager()
bar_format = u'{desc}{desc_pad}{count:d} {unit}{unit_pad}{elapsed} ' + \
             u'S:{count_1} ' + \
             u'[{elapsed}<{eta}, {rate:.2f}{unit_pad}{unit}/s]'
with manager.counter(desc='Steps', unit='steps', counter_format=bar_format) as pbar:

    goalctr = pbar.add_subcounter(42)

    for x in range(100):
        pbar.update()
        goalctr.update()
```

**Comment by edmcman** [comment]
More generally though I just want to output some statistics.  For instance, if I could say pbar.update(my_var1=10, my_var2=20) and reference those in the format, it would solve my use case too.

**Comment by avylove** [comment]
`count_n` only works with `bar_format`, not `counter_format`. I guess I could make it work with both. I guess I hadn't thought of this use case. Subcounters were designed for multicolored progress bars, where one color represents a subset of the total count. I didn't think of it terms of showing sub-statistics when no total was given.

Basically the method that add the fields for the subcounters never gets called when there is no total or the count is higher than the total. I can add that, but probably not in the next week or two.

A workaround for now would be to use  `bar_format` and set the total to the final number, if you know it, or a number you know you won't hit. Keep in mind, the `eta` field is based on total, so if the number is not known, eta doesn't really add value.

**Comment by edmcman** [comment]
Yes, that is exactly the bug.  My problem is unbounded so I am using `counter_format`.
What do you think of passing data through update args?

**Comment by avylove** [comment]
That seems like something that would be useful. Basically extra fields that get passed along to `format()`. Would just have to catch key errors and give a more useful exception like `Keyword 'my_var2' specified, but not provided'`

**Comment by edmcman** [comment]
Right.  Do you want me to take a first pass on implementing this?

**Comment by avylove** [comment]
You're welcome to. I won't have a chance to look at it for a week or two, but I have some other changes I need to incorporate so I'll try to get everything in for a new release.

**Comment by avylove** [comment]
I had a chance to look into it today. I'll be able to add arbitrary fields, but it's going to work a little differently than you were thinking. Something like this, where you'd specify a dictionary of additional fields when instantiating a manager or counter. The contents of the dictionary will will loaded every time `format()` is called, so the contents can be changed as long as the key specified in the counter or bar format isn't removed.

```python
import enlighten
import time

manager = enlighten.get_manager()
counter_format = u'{desc}{desc_pad}{count:d} {unit}{unit_pad}' + \
                 u'S:{my_var1} ' + \
                 u'[{elapsed}, {rate:.2f}{unit_pad}{unit}/s]{fill}'
my_fields = {'my_var1': 42}
with manager.counter(desc='Steps', unit='steps', counter_format=counter_format,
                     additional_fields=my_fields) as pbar:
    for x in range(100):
        time.sleep(0.05)
        my_fields['my_var1'] += 1
        pbar.update()
```

Do you think that will work?

**Comment by edmcman** [comment]
That would be great!  Obviously I didn't get a chance to work on it myself
🙂

**Comment by avylove** [comment]
Just added aa2b6f783d0337d562688abc554a22d45c85062b. Can you test it out?

**Comment by edmcman** [comment]
It works great.  Thanks!

**Comment by avylove** [comment]
Both `additional_fields` and subcounter fields for counter format were released with [1.5.0](https://github.com/Rockhopper-Technologies/enlighten/releases/tag/1.5.0)

**Comment by avylove** [comment]
In the latest release, I left ``additional_fields``, but added a new way to do this using keywords. It's described [here](https://python-enlighten.readthedocs.io/en/stable/patterns.html#user-defined-fields). You may want to also look at the new [status bar](https://python-enlighten.readthedocs.io/en/stable/examples.html#status-bars) feature.

**Comment by edmcman** [comment]
Thanks for the update!  I'll migrate to using keywords in case you decide to deprecate `additional_fields`
