### ISSUE TITLE
How can I close a progressbar when it's finished?

### ISSUE THREAD

**Issue by miratcan** [Rockhopper-Technologies/enlighten#15]
I have these progressbars but I want to close progressbars when they are finished. (I want to display only one progressbar at once)

<img width="1440" alt="Ekran Resmi 2020-04-02 23 10 32" src="https://user-images.githubusercontent.com/140968/78296913-3e792800-7537-11ea-9488-fd0e8fc0279b.png">

I tried bar.close() but did't worked. Are there any method to do this?

**Comment by avylove** [comment]
Just use `leave=False` when you create the progress bar. See the Counter [docs](https://python-enlighten.readthedocs.io/en/stable/api.html#enlighten.Counter) for more information.
