### ISSUE TITLE
terminal is left broken

### ISSUE THREAD

**Issue by Vigeant** [Rockhopper-Technologies/enlighten#16]
after the use of a progress bar in my python script the terminal is left broken. I need to type reset to recover.

**Comment by avylove** [comment]
Sorry to hear you're having issues. Can you provide more context? Which OS are you on, which terminal, what you are doing with the library, how is your terminal broken? Try the [examples](https://github.com/Rockhopper-Technologies/enlighten/tree/master/examples and see if you have the same issue.

**Comment by avylove** [comment]
Going to go ahead and close this, but if you still have issues, comment here and we can try to diagnose it.

**Comment by avylove** [comment]
@Vigeant , a fix was applied in [1.5.2](https://github.com/Rockhopper-Technologies/enlighten/releases/tag/1.5.2). I'm not sure if this was your issue or not, but please update and let me know if you still see the issue.
