### ISSUE TITLE
Not working well with pyinstaller

### ISSUE THREAD

**Issue by camprevail** [Rockhopper-Technologies/enlighten#17]
Built my application with pyinstaller. Works fine without it, but pyinstaller causes output like so:
```
Verifying - src\custom_charts\A thing called LOVE\A thing called LOVE.ssc
  2%|█▌                                                                                     |   2/113 [00:00<00:07, 16.99 files/s]
Verifying - src\custom_charts\Absurd Gaff\Absurd Gaff.ssc
Verifying - src\custom_charts\Air\Air.ssc
  4%|███                                                                                    |   4/113 [00:00<00:07, 15.49 files/s]
Verifying - src\custom_charts\ANTHEM LANDING -A mix-\ANTHEM LANDING -A mix-.ssc
Verifying - src\custom_charts\ANTHEM LANDING -N mix-\ANTHEM LANDING -N mix-.ssc
  5%|████▌                                                                                  |   6/113 [00:00<00:07, 15.67 files/s]
Verifying - src\custom_charts\Ark Ouroboros\Ark Ouroboros.ssc
Verifying - src\custom_charts\Astrogazer\Astrogazer.ssc
  7%|██████                                                                                 |   8/113 [00:00<00:06, 16.27 files/s]
Verifying - src\custom_charts\Bad Maniacs\Bad Maniacs.ssc
Verifying - src\custom_charts\Boomy and The Boost\Boomy and The Boost.ssc
Verifying - src\custom_charts\Change the World\Change the World.ssc
 10%|████████▌                                                                              |  11/113 [00:01<00:06, 17.43 files/s]
```

**Comment by avylove** [comment]
Thanks for reporting!
It looks like it's not properly detecting the screen width.
What OS and Python version are you running?

**Comment by avylove** [comment]
I tested pyinstaller on Linux and can't reproduce the issue. My guess is you're on Windows and not including the dynamic imports for Jinxed. See [this](https://github.com/Rockhopper-Technologies/jinxed/issues/1) and [this](https://stackoverflow.com/questions/59021200/blessed-curses-controls-dont-work-with-pyinstaller-missing-vtwin10) for more information. In the second one, In the second post I including a dynamic fix you can put in your pyinstaller spec file.

Let me know if this solves your issue.

**Comment by camprevail** [comment]
Thanks, will try. Yeah I'm on windows 10 1909 with python 3.7.

**Comment by camprevail** [comment]
Yep, that worked! Much thanks.

**Comment by camprevail** [comment]
Having another pyinstaller related issue. After calling `manager.stop()` and `sys.stdout.flush()`, it doesn't properly 'reset' the terminal and prints some junk instead of a newline. 
```[29;1H[29;1H[29;1H[29;1H[?12l[?25h[1;31r[31;1HD:\Museca-Plus\git\museca-plus>████████████| 1/1 [00:02<00:00, 0.49 files/s]```

**Comment by avylove** [comment]
@camprevail Can you open a new issue and provide a code sample? Also, what console are you using? Is it winin an IDE, powershell, or regular command prompt? Thanks!

**Comment by avylove** [comment]
Opened #21
