### ISSUE TITLE
"Signal only works in main thread" issue

### ISSUE THREAD

**Issue by altskop** [Rockhopper-Technologies/enlighten#2]
Hi,

It looks like it is impossible to use the module in a Flask app. Requests in Flask are executed in threads, and calling the `update()` method of a Counter is only possible in main thread.

Some relevant logs:

```
  File "/app/executors/base.py", line 74, in _run
    pbar.update()
  File "/usr/local/lib/python3.6/site-packages/enlighten/_counter.py", line 394, in update
    self.refresh(elapsed=currentTime - self.start)
  File "/usr/local/lib/python3.6/site-packages/enlighten/_counter.py", line 374, in refresh
    flush=flush, position=self.position)
  File "/usr/local/lib/python3.6/site-packages/enlighten/_manager.py", line 369, in write
    self._set_scroll_area()
  File "/usr/local/lib/python3.6/site-packages/enlighten/_manager.py", line 228, in _set_scroll_area
    signal.signal(signal.SIGWINCH, self._resize_handler)
  File "/usr/local/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

**Comment by avylove** [comment]
This is really a product of how signal handling is done in Python and signal is required to handle window resizing.

The ideal solution would be to have the manager in the main thread and pass updates from the child threads. This should be possible with Flask by running flask in a child thread or subprocess. This would also be the best solution if more than one thread needs to have progress bars or counters.

Do you have a need to account for resizing the terminal window? I could add an option to disable resizing support. That way signal would not get called. It's not the ideal solution, but if you don't need resizing support and only have one thread that needs progress bars, it would be an easy way for you to continue. Let me know if that would help.

**Comment by avylove** [comment]
[Version 1.2.0](https://github.com/Rockhopper-Technologies/enlighten/releases/tag/1.2.0) is now with the ''no_resize'' argument for the Manager class. I'm going to go ahead and close this. When I get a chance, I'll try to add a threaded example. Let me know if you run into any more issues.

**Comment by avylove** [comment]
Haven't created a threading example yet, but I did create a multiprocessing [example](https://github.com/Rockhopper-Technologies/enlighten/blob/master/examples/muliprocessing_queues.py) which would be similar using [queue.Queue](https://docs.python.org/3/library/queue.html#queue.Queue).
