### ISSUE TITLE
Show status of variable while updating the progress var

### ISSUE THREAD

**Issue by jiwidi** [Rockhopper-Technologies/enlighten#22]
**Describe the solution you'd like**
Hi! I would like to use the library to also display the last value of a variable on each loop execution.

Lets say for example:

```python
import time
import enlighten

pbar = enlighten.Counter(total=100, desc='Basic', unit='ticks')
i=0
for num in range(100):
    i+=1
    time.sleep(0.1)  # Simulate work
    pbar.update()
```

Is there anyway to display the value of `i` (being changed on every iteration) on the progress bar?

**Comment by avylove** [comment]
You're in luck, that feature was added recently.

    import time
    import enlighten

    bar_format = u'{desc}{desc_pad} i:{i} {percentage:3.0f}%|{bar}| {count:{len_total}d}/{total:d} ' + \
                 u'[{elapsed}<{eta}, {rate:.2f}{unit_pad}{unit}/s]'

    my_fields = {'i': 0}
    pbar = enlighten.Counter(total=100, desc='Basic', unit='ticks',
                             bar_format=bar_format, additional_fields=my_fields)
                             
    for num in range(100):
        my_fields['i'] += 1
        time.sleep(0.1)  # Simulate work
        pbar.update()

It might also be good to add an example of this in the docs.

**Comment by avylove** [comment]
I actually reworked this a bit in the last release and now you can specify additional user-defined fields as keywords. It's described [here](https://python-enlighten.readthedocs.io/en/stable/patterns.html#user-defined-fields).
