### ISSUE TITLE
Render the progress bar before the first update/tick

### ISSUE THREAD

**Issue by archiif** [Rockhopper-Technologies/enlighten#40]
**Is your feature request related to a problem? Please describe.**
In cases where each cycle takes a decent amount of time to complete, the progress bar will not be rendered until the first `pbar.update` which might take a while.

**Describe the solution you'd like**
So, a way to force the progress bar to render ahead of time would be useful.

**Comment by avylove** [comment]
Counters, unlike status bars aren't drawn when created because there could be subcounters added in the next step that change the format of the bars. `pbar.refresh()` should provide you with what you need. Let me know if that works for you.

**Comment by archiif** [comment]
Thank you, that did the trick!
