### ISSUE TITLE
Not compatible with pytorch-cuda on windows platform

### ISSUE THREAD

**Issue by TheAutumnOfRice** [Rockhopper-Technologies/enlighten#49]
**Describe the bug**
As far as I've tested, it is a bug that only existed on windows platform.
If a pytorch (with cuda) module is imported, all the print functions that between `counter.update()` will malfunction. In detail, if there's only one line print between `update()`, the last printed text will be replaced by the new one; if there are multiple lines, the progressbar will be replaced and the progressbar will be rewritten at a new line when `update` is called.

What confused me is that the bug only occurs in cuda-version-pytroch and only on windows platform. In other words, a cpu version of pytorch will not encounter it. I guess the cuda initialization progress may conflict with enlighten.

**To Reproduce**
#### No torch, no bug.
code:
```python
import enlighten
import time

manager = enlighten.get_manager()
A = manager.counter(total=10)
for i in range(10):
    print("Processing:",i)
    time.sleep(0.1)
    A.update()
A.close()
```
output:
![image](https://user-images.githubusercontent.com/52663977/178090959-e05a4451-3544-48fc-8fe2-287cea22d2f5.png)
#### Torch (cuda version), BUG!
```python
import enlighten
import time
import torch
print(torch.__version__)
manager = enlighten.get_manager()
A = manager.counter(total=10)
for i in range(10):
    print("Processing:",i)
    time.sleep(0.1)
    A.update()
A.close()
```
output:
![image](https://user-images.githubusercontent.com/52663977/178090991-fafed408-72d6-475b-b23c-58a0793314cc.png)
#### Torch (cpu version), no bug
(The same code with the last one)
![image](https://user-images.githubusercontent.com/52663977/178091026-db4c05d9-2676-45de-9579-7d59f82348d6.png)
**Environment (please complete the following information):**
 - Enlighten Version: 1.10.2
 - OS and version: win10
 - Console application: cmd, Pycharm Terminal and Powershell

**Addition**
I've tested it on my remote linux server. It works pretty well under all conditions.

**Comment by avylove** [comment]
Thanks for reporting. This is going to be difficult because I don't have a like platform to troubleshoot on. I think the issue may be that the console mode is not getting set correctly. Can you add this code and let me know if there are any differences between the cuda version and the non-cuda version? 

```python

# Add after manager = enlighten.get_manager()

import sys
from msvcrt import get_osfhandle
import jinxed
from jinxed.win32 import get_console_mode

# Check if stdout is redirected
print(sys.stdout is sys.__stdout__)

# Check for errors in blessed
print(manager.term.errors)

# See what module jinxed is using for terminfo
print(jinxed._terminal.TERM.terminfo.__name__)

# Check console mode
print(get_console_mode(get_osfhandle(sys.stdout.fileno())))

```

**Comment by TheAutumnOfRice** [comment]
Thanks for your reply!

**non-cuda version output**
```
1.12.0+cpu
True
["parameters: kind=None, stream=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>, force_styling=False"]
jinxed.terminfo.vtwin10
7
```
**cuda-version output**
```
1.12.0+cu113
False
['parameters: kind=None, stream=<colorama.ansitowin32.StreamWrapper object at 0x000001D9B64BF288>, force_styling=False', 'Output stream is not a default stream']
jinxed.terminfo.vtwin10
7
```

**Comment by avylove** [comment]
What that tells us is stdout is getting wrapped by colorama. Try specifying the real stdout when invoking the manager.

```python
manager = enlighten.get_manager(stream=sys.__stdout__)
```

**Comment by TheAutumnOfRice** [comment]
It works! Thank you very very much avylove!

**Comment by avylove** [comment]
Glad to hear it! I'm wondering if I should make `sys.__stdout__` the default rather than `sys.stdout`. 99% of the time it makes no difference, but in some corner cases, like this, it can make a difference.

**Comment by avylove** [comment]
Changed default from `sys.stdout` to `sys.__stdout__` in [1.11.0](https://github.com/Rockhopper-Technologies/enlighten/releases/tag/1.11.0).
