### ISSUE TITLE
Set scroll area when calling Counter() directly

### ISSUE THREAD

**Issue by ngriffiths13** [Rockhopper-Technologies/enlighten#52]
**Describe the bug**
When using enlighten and logging, the progress bar is being interrupted everytime I log.

```INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
Backtesting  18%|█████████████████████▊                                                                                                   |  9/50 [00:00<00:01, 81.32 bars/s]INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
INFO:__main__:LOG
Backtesting  36%|███████████████████████████████████████████▌                                                                             | 18/50 [00:00<00:00, 81.41 bars/s]INFO:__main__:LOG
```

**To Reproduce**
```import enlighten
import logging
import time

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

my_list = list(range(50))
pbar = enlighten.Counter(total=len(my_list), desc="Backtesting",
                                      unit="bars", color="blue")

for l in my_list:
    time.sleep(.01)
    logger.info("LOG")
    pbar.update()
```

**Environment (please complete the following information):**
 - Enlighten Version: 1.11.1
 - OS and version: MacOS M1 Chip
 - Console application: iterm2
 - Special Conditions: Running with poetry in python 3.10.5

**Comment by ngriffiths13** [comment]
Ah okay that did the trick. Setting it automatically might be nice. Or at least making it clear that it doesn't in the documentation. Thanks!

**Comment by avylove** [comment]
In [1.12.0](https://github.com/Rockhopper-Technologies/enlighten/releases/tag/1.12.0) calling the Counter class directly will now behave the same as using a manager. References to calling directly have been removed from the documentation and it may be dropped in a future release.
