### ISSUE TITLE
Notebook manager fails at stopping when counters are closed

### ISSUE THREAD

**Issue by juancitotrucupey** [Rockhopper-Technologies/enlighten#53]
**Describe the bug**
The NotebookManager iterates over the existing counters when is stopping, but if there are no available counters it will fail. Hence, is necessary to check if there are existing counters before adding a new line break for each number that is not a position.

```
positions = self.counters.values()
for num in range(max(positions), 0, -1):
    if num not in positions:
        self._output[num - 1] = '  <br>'
```

**To Reproduce**
Run the following code snippet in a jupyter notebook cell

```
import enlighten
from time import sleep
with enlighten.get_manager() as enlighten_manager:
    n_total = 20
    counter_1 = enlighten_manager.counter(
        total=n_total,
        desc=f"amount of iteration {n_total}",
        color="green",
        leave=False,
    )
    # Create counter
    timelaps = 0.2
    for ii in range(n_total):
        sleep(timelaps)
        counter_1.update()
    counter_1.close(clear=True)

``` 
 And you will get this stack trace:

```
     (...)
     90 positions = self.counters.values()
     ---> 93 for num in range(max(positions), 0, -1):
     94     if num not in positions:
     95         self._output[num - 1] = '  <br>'

ValueError: max() arg is an empty sequence
```

**Environment (please complete the following information):**

 - Enlighten Version: 1.11.1
 - OS and version: Ubuntu 
 - Console application: jupyter ntebook

**Additional context**
I one liner solve it for me, I checked if `positions` was not empty and then added the corresponding line breaks:

```
    def stop(self):
        # See parent class for docstring

        if not self.enabled:
            return

        positions = self.counters.values()

        if len(positions) > 0:
            for num in range(max(positions), 0, -1):
                if num not in positions:
                    self._output[num - 1] = '  <br>'

        for counter in self.counters:
            counter.enabled = False

        self._flush_streams()
```

**Comment by avylove** [comment]
Thanks for reporting!
Fixed in https://github.com/Rockhopper-Technologies/enlighten/commit/fbd38b566bf5f3359c64f5be272802e9c42b6204  and released in [1.11.2](https://github.com/Rockhopper-Technologies/enlighten/releases/tag/1.11.2)
Please let me know if you have any more issues.
