### ISSUE TITLE
Progress bar only show up with first call of `update`

### ISSUE THREAD

**Issue by DanielHabenicht** [Rockhopper-Technologies/enlighten#55]
**Describe the bug**

A progress bar with an inital value should be displayed straight away instead of waiting for the next `update` call. 

![bug_enlighten](https://user-images.githubusercontent.com/13590797/222901503-31f7e093-04f7-472c-a662-d0b1966aff2b.gif)

**To Reproduce**
```python
import logging
from time import sleep
import enlighten

done = 20
jobs = range(10000)

logging.warning("Before init")


manager = enlighten.get_manager()
results = []
bar_experiments = manager.counter(
    total=len(jobs), desc="Experiments", unit="experiments", leave=False, count=done
)
logging.warning("After init")

sleep(5)
logging.warning("After sleep")

for i in jobs:
    logging.warning(i)
    bar_experiments.update()
    # sleep(0.01)
```

**Environment (please complete the following information):**
 - Enlighten Version: 1.11.2
 - OS and version: Windows 11, but using a devcontainer on WSL2, base image `mcr.microsoft.com/devcontainers/python:0-3.10`
 - Console application: VS Code Terminal
 - Special Conditions: none?

**Additional context**
I've only seen it on the GIF now, but if I `clear` the terminal before running the script the log output from before calling the manager gets cut off.

**Comment by avylove** [comment]
I'm not sure this is a bug. There was a decision not to draw progress bars before the first refresh because there is no way to determine if the user intends to add subcounters or not. It's a little different for status bars because there are no sub-statusbars, so we can draw them right away.
However, you can add `bar_experiments.refresh()` after creating the bar to draw it.

**Comment by DanielHabenicht** [comment]
Thanks for the fast answer! 

I was almost thinking about this probably being an intentional decision. That's ok for me, maybe we should add the `refresh()` information to the `count` documentation on the Counter? 
![image](https://user-images.githubusercontent.com/13590797/222922991-8f43dfd9-8da6-4127-996f-9e46756e1478.png)
~~I have't seen it immediatly but maybe there is a good place to document that all progress bars only draw on the first `update()`?~~ Found it. Maybe this box can be added to the `enlighten.Counter` docs too: 
![image](https://user-images.githubusercontent.com/13590797/222923208-1e0719c5-bbf4-4930-ac22-92a026d4ac4a.png)

**Comment by avylove** [comment]
Thanks. If it will make it clearer I can add it. It might also be good to have in the FAQ.
