### ISSUE TITLE
Doc talks about "manager"'s counter but then uses module-level function

### ISSUE THREAD

**Issue by raffaem** [Rockhopper-Technologies/enlighten#63]
[docs says](https://python-enlighten.readthedocs.io/en/stable/examples.html):

> For a basic progress bar, invoke the [Manager.counter](https://python-enlighten.readthedocs.io/en/stable/api.html#enlighten.Manager.counter) method.

But in the example it calls a module-level function, not the manager's one:

```
import enlighten
[...]
manager = enlighten.get_manager()
pbar = enlighten.counter(total=100, desc='Basic', unit='ticks')
```

In the next example, the manager's functions are instead called:
```
import time
import enlighten
[...]
manager = enlighten.get_manager()
ticks = manager.counter(total=100, desc='Ticks', unit='ticks')
tocks = manager.counter(total=20, desc='Tocks', unit='tocks')
```

**Comment by avylove** [comment]
Thanks for reporting! Looks like a change in Read the Docs also broke document building since the last release.  Both issues fixed as of 1.12.2.
