### ISSUE TITLE
Output gets scrambled when the number of progress bars exceeds the terminal height

### ISSUE THREAD

**Issue by Zac-Hodge** [Rockhopper-Technologies/enlighten#68]
**Describe the bug**
When the number of progress bars (status/progress/counter) exceeds the height of the terminal the output gets scrambled. Ideally you should just be able to scroll up to view them (and any prints/output). This feels like it could be a known limitation but it would be good to see it acknowledged somewhere.

**To Reproduce**
Run the 'multiprocessing_queues.py' example with a really short terminal (or increase the number of processes/bars).

**Environment (please complete the following information):**
 - Enlighten Version: 1.12.4
 - OS and version: Windows 10
 - Console application: Command Prompt, Windows PowerShell, VS Code Terminal
 - Special Conditions: N/A

**Additional context**
Thanks for making Enlighten! I've really enjoyed using it!

**Comment by avylove** [comment]
Thanks for reporting! I'm not sure if scroll back is possible. The bars are drawn within the scroll region and the start of the scroll region is limited to the size of the terminal. At least Enlighten limits it this way, but I don't even think you can pass negative numbers to CSR. It might be worth experimenting a bit. For now, we can probably add something in the FAQ.

Potentially, on some platforms (Probably not Windows), you could increase the terminal height if there are more bars than there is room for, but it's hard to say how that could effect end users.

**Comment by avylove** [comment]
Added [FAQ entry](https://python-enlighten.readthedocs.io/en/stable/faq.html#why-does-the-output-get-scrambled-when-the-number-of-progress-bars-exceeds-the-terminal-height) in [1.13.0](https://github.com/Rockhopper-Technologies/enlighten/releases/tag/1.13.0)

I'm not sure we'll be able to do more than that. So I'm going to go ahead and close this.
