### ISSUE TITLE
Invalid handle in PyCharm (Windows)

### ISSUE THREAD

**Issue by 4sfaloth** [Rockhopper-Technologies/enlighten#8]
Hi,
I am running enlighten-1.3.3 on Windows under Pycharm, and I always get a `OSError: [WinError 6] The handle is invalid.` error when I try to instantiate either a Counter or a Manager.
I see there were similar issues raised [here ](https://github.com/Rockhopper-Technologies/enlighten/issues/3) and [here](https://github.com/Rockhopper-Technologies/enlighten/issues/4) but if I understood correctly they should be fixed in this version.

Did I misunderstand the other issues and is Pycharm simply not supported by enlighten? Or is there some way to fix this issue?
Thanks

**Comment by avylove** [comment]
It's working under PyCharm on Windows 10 for me. Can you post an example of what you're running and the full traceback? What version of Windows?

**Comment by 4sfaloth** [comment]
@avylove thanks for the fast reply.

It happens when I try to instatiate a Counter or Manager object. For instance when running the example snipped provided in the docs

```
import time
import enlighten

pbar = enlighten.Counter(total=100, desc='Basic', unit='ticks')
for num in range(100):
    time.sleep(0.1)  # Simulate work
    pbar.update()
```
I get this traceback

```
Traceback (most recent call last):
  File "C:/dev/vbresearch-python/support_scripts/test_enlighten.py", line 4, in <module>
    pbar = enlighten.Counter(total=100, desc='Basic', unit='ticks')
  File "C:\Users\filipe.morais\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\enlighten\counter.py", line 31, in __init__
    counter_class=self.__class__, set_scroll=False)
  File "C:\Users\filipe.morais\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\enlighten\_manager.py", line 397, in get_manager
    return Manager(stream=stream, counterclass=counterclass, **kwargs)
  File "C:\Users\filipe.morais\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\enlighten\_manager.py", line 78, in __init__
    self.term = Terminal(stream=self.stream)
  File "C:\Users\filipe.morais\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\enlighten\_terminal.py", line 32, in __init__
    super(Terminal, self).__init__(*args, **kwargs)
  File "C:\Users\filipe.morais\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\enlighten\_win_terminal.py", line 144, in __init__
    enable_vt_mode(self.stream_fh)
  File "C:\Users\filipe.morais\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\enlighten\_win_terminal.py", line 109, in enable_vt_mode
    KERNEL32.GetConsoleMode(filehandle, ctypes.byref(current_mode))
  File "C:\Users\filipe.morais\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\enlighten\_win_terminal.py", line 71, in _check_bool
    raise ctypes.WinError(ctypes.get_last_error())
OSError: [WinError 6] The handle is invalid.
```
Using Windows 10 Enterprise, version 10.0.16299 Build 16299

**Comment by 4sfaloth** [comment]
@avylove it works fine if I run it from anaconda prompt. Just not on PyCharm

**Comment by avylove** [comment]
I see where this is happening and I could add some logic to catch it, though the resolution may be to disable terminal codes. However, I can't reproduce it. What version of PyCharm are you running?

**Comment by 4sfaloth** [comment]
> So I'm guessing you mean it's not working within the Python console in PyCharm? I got the same error. It does work in the PyCharm terminal.
> 
Hum... actually no, for me it does not seem to work in the PyCharm terminal either (ie: when you press 'Run' button inside PyCharm, right?)

**Comment by avylove** [comment]
Sorry for the delay. Ok, so that works when running your code through PyCharm? I can add something to the FAQ for that. It seems to work natively in the terminal. So the only issue is the Python console. I'm not sure if that's supportable, but in a future version it should disable the progress bars rather than throwing an exception, so I can keep this issue open fow now.

**Comment by avylove** [comment]
Glad you are getting good use of it. Spread the word :-)

Updated FAQ in ff711caa334fee425b5200fc813046dc69e51dcb.

**Comment by avylove** [comment]
Enlighten should fail gracefully now (1.4.0) when the terminal is not supported. This includes the PyCharm Python console. Basically, it won't break anything, but there will be no progress bars. Let me know if you have any other issues.
